AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-radiko

  Sample SAM Template for lambda-radiko

Parameters:
  BucketName:
    Type: String
    Default: radiko-download
  LogGroupName:
    Type: String
    Default: /aws/lambda/lambda-radiko

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:
  RadikoDownloadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: radiko_download/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      MemorySize: 512
      Timeout: 600
      Architectures:
        - arm64
      Layers:
        - !Ref FFmpegLayer
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName
      LoggingConfig:
        LogGroup: !Ref LogGroupName

  RadikoProgramFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: radiko_program/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      MemorySize: 128
      Timeout: 60
      Architectures:
        - arm64
      Environment:
        Variables:
          RADIKO_DL_FUNC_NAME: !GetAtt RadikoDownloadFunction.Arn
          RADIRU_DL_FUNC_NAME: !GetAtt RadiruDownloadFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref RadikoDownloadFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RadiruDownloadFunction
      LoggingConfig:
        LogGroup: !Ref LogGroupName

  FFmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: FFmpegLayer
      Description: FFmpeg binary
      ContentUri: layers/
      CompatibleRuntimes:
        - ruby3.3

  RadikoDownloadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RadikoDownloadFunction:
    Description: Radiko Download Lambda Function ARN
    Value: !GetAtt RadikoDownloadFunction.Arn
  RadikoDownloadFunctionIamRole:
    Description: Implicit IAM Role created for Radiko Download function
    Value: !GetAtt RadikoDownloadFunctionRole.Arn
