AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-line-notify

  Sample SAM Template for lambda-line-notify

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  LineNotifyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: line_notify/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      Environment:
        Variables:
          LINE_SECRET_REGION: !Ref AWS::Region
          LINE_SECRET_NAME: !Ref SecretName
      Policies:
        - AWSLambdaBasicExecutionRole
        - SecretsManagerReadPolicy:
            SecretName: !Ref SecretName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LineNotifyFunction:
    Description: "LINE Notify Lambda Function ARN"
    Value: !GetAtt LineNotifyFunction.Arn
  LineNotifyFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LineNotifyFunctionRole.Arn
