AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-podcast-download

Parameters:
  BucketName:
    Type: String
    Default: podcast-download
  LogGroupName:
    Type: String
    Default: /aws/lambda/podcast-download

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:
  PodcastDownloadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: podcast-download
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      MemorySize: 512
      Timeout: 600
      Architectures:
        - arm64
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
      Policies:
        - S3WritePolicy:
            BucketName: !Ref BucketName
      LoggingConfig:
        LogGroup: !Ref LogGroupName
