AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Notify NHK programs info to Discord channel

Parameters:
  ApiKeyParameterName:
    Type: String
  WebhookUrlParameterName:
    Type: String
  ExcludeBS8KPrograms:
    Type: String
    Default: True
  LambdaExtensionSsmLayerArn:
    Type: String
    Default: 'arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:12'

Resources:
  NotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      Timeout: 30
      MemorySize: 128
      Architectures:
        - arm64
      Layers:
        - Ref: LambdaExtensionSsmLayerArn
      Environment:
        Variables:
          API_KEY_PARAMETER_NAME: !Ref ApiKeyParameterName
          WEBHOOK_URL_PARAMETER_NAME: !Ref WebhookUrlParameterName
          EXCLUDE_BS8K_PROGRAMS: !Ref ExcludeBS8KPrograms
      Policies:
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: !Ref ApiKeyParameterName
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: !Ref WebhookUrlParameterName
