AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Notify AWS cost to Discord channel

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Parameters:
  DiscordWebhookUrl:
    Type: String

Resources:
  NotifyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: ruby3.3
      Architectures:
        - arm64
      Environment:
        Variables:
          DISCORD_WEBHOOK_URL: !Ref DiscordWebhookUrl
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ce:GetCostAndUsage'
              Resource: '*'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NotifyFunction:
    Description: 'Discord AWS cost notify Lambda function ARN'
    Value: !GetAtt NotifyFunction.Arn
  NotifyFunctionIamRole:
    Description: 'Implicit IAM Role created for Discord AWS cost notify function'
    Value: !GetAtt NotifyFunctionRole.Arn
